import pandas as pd

smartphones_data = [
    {"ProductId": 1, "Product_Name": "iPhone 12", "Desc": "Apple smartphone", 
      "Price": 799, "Offer": "10% off", "Review": 4.5,
     "Operating_System": "iOS", "Display_Size": "6.1-inch Super Retina XDR display", 
     "Processor": "A14 Bionic chip", "Camera": "Dual-camera system", 
     "Security": "Face ID", "Design": "Ceramic Shield front cover", 
     "Durability": "Water and dust resistant (IP68)", "Connectivity": "5G capable", 
     "Charging": "Wireless charging", "Color_Options": "Available in multiple colors"},
    {"ProductId": 2, "Product_Name": "Samsung Galaxy S20", "Desc": "Android smartphone", 
     "Price": 899, "Offer": "15% off", "Review": 4.7,
     "Operating_System": "Android", "Display_Size": "6.2-inch Quad HD+ Dynamic AMOLED display", 
     "Processor": "Snapdragon 865 processor", "Camera": "Triple-camera system", 
     "Security": "Ultrasonic fingerprint sensor", "Connectivity": "5G capable", 
     "Special_Features": "Wireless PowerShare", 
     "Durability": "IP68 water and dust resistance", 
     "Charging": "Fast charging", "Storage_Options": "Expandable storage"},
    {"ProductId": 3, "Product_Name": "Google Pixel 5", "Desc": "Android smartphone", 
     "Price": 699, "Offer": "No offer", "Review": 4.6,
     "Operating_System": "Android", "Display_Size": "6.0-inch OLED display", 
     "Processor": "Snapdragon 765G processor", "Camera": "Dual-camera system", 
     "Security": "Rear-mounted fingerprint sensor", "Connectivity": "5G capable", 
     "Special_Features": "Pure Android experience", 
     "Durability": "IP68 water and dust resistance", 
     "Charging": "Fast charging", "Color_Options": "Just Black, Sorta Sage"},
    {"ProductId": 4, "Product_Name": "OnePlus 8 Pro", "Desc": "Android smartphone", 
     "Price": 899, "Offer": "10% off", "Review": 4.8,
     "Operating_System": "Android", "Display_Size": "6.78-inch Fluid AMOLED display", 
     "Processor": "Snapdragon 865 processor", "Camera": "Quad-camera system", 
     "Security": "In-display fingerprint sensor", "Connectivity": "5G capable", 
     "Special_Features": "Fast charging (Warp Charge 30T)", 
     "Durability": "Water and dust resistant (IP68)", 
     "Charging": "Wireless charging", "Color_Options": "Glacial Green, Ultramarine Blue, Onyx Black"}
    # Add more smartphone data here
]

laptops_data = [
    {"ProductId": 201, "Product_Name": "MacBook Pro 13", "Desc": "Apple laptop", 
     "Price": 1299, "Offer": "No offer", "Review": 4.8,
     "Display_Size": "13.3 inches", "Processor": "Intel Core i5 processor", 
     "RAM": "8GB RAM", "Storage": "256GB SSD storage", 
     "Graphics": "Intel Iris Plus Graphics", "Special_Features": "Touch Bar and Touch ID", 
     "Ports": "Four Thunderbolt 3 (USB-C) ports", "Operating_System": "macOS", 
     "Battery_Life": "Up to 10 hours of battery life", "Weight": "Weighs just 3.1 pounds"},
    {"ProductId": 202, "Product_Name": "Dell XPS 13", "Desc": "Dell laptop", 
     "Price": 1399, "Offer": "10% off", "Review": 4.6,
     "Display_Size": "13.4 inches", "Processor": "Intel Core i7 processor", 
     "RAM": "16GB RAM", "Storage": "512GB SSD storage", 
     "Graphics": "Intel Iris Xe Graphics", "Security": "Fingerprint reader", 
     "Connectivity": "Killer Wi-Fi 6", "Operating_System": "Windows 10 Home", 
     "Keyboard": "Backlit keyboard", "Design": "Thin and light design"},
    {"ProductId": 203, "Product_Name": "HP Spectre x360", "Desc": "Convertible laptop", 
     "Price": 1499, "Offer": "15% off", "Review": 4.7,
     "Display_Size": "13.3 inches", "Processor": "Intel Core i7 processor", 
     "RAM": "16GB RAM", "Storage": "512GB SSD storage", 
     "Graphics": "Intel Iris Xe Graphics", "Special_Features": "360-degree hinge", 
     "Operating_System": "Windows 10 Home", 
     "Battery_Life": "Up to 12 hours of battery life", "Weight": "Weighs just 2.87 pounds"},
    {"ProductId": 204, "Product_Name": "Lenovo ThinkPad X1 Carbon", "Desc": "Business laptop", 
     "Price": 1699, "Offer": "No offer", "Review": 4.9,
     "Display_Size": "14 inches", "Processor": "Intel Core i7 processor", 
     "RAM": "16GB RAM", "Storage": "1TB SSD storage", 
     "Graphics": "Intel Iris Xe Graphics", "Security": "Fingerprint reader", 
     "Connectivity": "Wi-Fi 6", "Operating_System": "Windows 10 Pro", 
     "Keyboard": "Spill-resistant backlit keyboard", "Design": "Carbon fiber construction"}
    # Add more laptop data here
]

smartwatch_data = [
    {"ProductId": 301, "Product_Name": "Apple Watch Series 6", "Desc": "Smartwatch by Apple", 
     "Price": 399, "Offer": "No offer", "Review": 4.9,
     "OS": "watchOS", "Display": "Always-On Retina display", 
     "Chip": "S6 SiP with 64-bit dual-core processor", "Health": "ECG and blood oxygen sensors", 
     "Fitness": "Activity tracking with GPS", "Waterproof": "Water resistant up to 50 meters", 
     "Connectivity": "LTE and Wi-Fi", "Battery": "Up to 18 hours of battery life"},
    {"ProductId": 302, "Product_Name": "Samsung Galaxy Watch 3", "Desc": "Smartwatch by Samsung", 
     "Price": 429, "Offer": "10% off", "Review": 4.7,
     "OS": "Tizen", "Display": "Circular Super AMOLED display", 
     "Chip": "Exynos 9110 Dual-core processor", "Health": "ECG and blood pressure monitoring", 
     "Fitness": "Advanced workout tracking", "Waterproof": "Water resistant up to 50 meters", 
     "Connectivity": "LTE and Bluetooth", "Battery": "Up to 2 days of battery life"},
    {"ProductId": 303, "Product_Name": "Fitbit Versa 3", "Desc": "Smartwatch by Fitbit", 
     "Price": 229, "Offer": "15% off", "Review": 4.5,
     "OS": "Fitbit OS", "Display": "AMOLED display", 
     "Chip": "N/A", "Health": "24/7 heart rate tracking", 
     "Fitness": "Built-in GPS for activity tracking", "Waterproof": "Water resistant up to 50 meters", 
     "Connectivity": "Bluetooth", "Battery": "Up to 6 days of battery life"},
    {"ProductId": 304, "Product_Name": "Garmin Fenix 6 Pro", "Desc": "Outdoor smartwatch by Garmin", 
     "Price": 699, "Offer": "No offer", "Review": 4.8,
     "OS": "Garmin OS", "Display": "Sunlight-readable display", 
     "Chip": "N/A", "Health": "Advanced sleep monitoring and stress tracking", 
     "Fitness": "Built-in navigation sensors", "Waterproof": "Water resistant up to 100 meters", 
     "Connectivity": "Bluetooth and Wi-Fi", "Battery": "Up to 14 days of battery life"}
    # Add more smartwatch data here
]
washing_machines_data = [
    {"ProductId": 1, "Product_Name": "Samsung Front Load Washer", "Desc": "Front load washing machine with advanced features", 
     "Price": 899, "Offer": "10% off", "Review": 4.7,
     "Capacity": "5.0 cu. ft.", "Cycle_Options": "Multiple wash cycles including quick wash and heavy duty", 
     "Energy_Efficiency": "ENERGY STAR certified", "Spin_Speed": "1200 RPM", 
     "Load_Sensing": "Smart load sensing technology", "Vibration_Control": "Advanced vibration control technology", 
     "Motor_Type": "Inverter motor for quiet and efficient operation", 
     "Water_Usage": "Optimized water usage with automatic load detection"},
    {"ProductId": 2, "Product_Name": "LG Top Load Washer", "Desc": "Top load washing machine with large capacity and smart features", 
     "Price": 799, "Offer": "15% off", "Review": 4.6,
     "Capacity": "5.3 cu. ft.", "Cycle_Options": "Various wash cycles including TurboWash and ColdWash", 
     "Energy_Efficiency": "Energy Star certified", "Spin_Speed": "1100 RPM", 
     "Load_Sensing": "Intelligent load sensing technology", "Vibration_Control": "TrueBalance anti-vibration system", 
     "Motor_Type": "Direct Drive motor for durability and efficiency", 
     "Water_Usage": "Smart water usage optimization"},
    {"ProductId": 3, "Product_Name": "Whirlpool Front Load Washer", "Desc": "High-efficiency front load washer for thorough cleaning", 
     "Price": 849, "Offer": "No offer", "Review": 4.8,
     "Capacity": "4.5 cu. ft.", "Cycle_Options": "Multiple wash cycles including sanitize and allergen cycles", 
     "Energy_Efficiency": "Energy Star certified", "Spin_Speed": "1300 RPM", 
     "Load_Sensing": "Precision load sensing technology", "Vibration_Control": "Advanced vibration control mechanism", 
     "Motor_Type": "Induction motor for reliability and performance", 
     "Water_Usage": "Efficient water consumption management"},
    {"ProductId": 4, "Product_Name": "GE Top Load Washer", "Desc": "Top load washer with large capacity and advanced features", 
     "Price": 899, "Offer": "5% off", "Review": 4.7,
     "Capacity": "5.0 cu. ft.", "Cycle_Options": "Variety of wash cycles including Deep Fill and Quick Wash", 
     "Energy_Efficiency": "Energy Star certified", "Spin_Speed": "1150 RPM", 
     "Load_Sensing": "Adaptive load sensing technology", "Vibration_Control": "QuietWash technology for reduced noise", 
     "Motor_Type": "Hybrid motor system for power and efficiency", 
     "Water_Usage": "Efficient water usage with intelligent sensing"}
]

combined_data = smartphones_data + laptops_data + smartwatch_data + washing_machines_data

def get_data():
    return  pd.DataFrame(combined_data)